server:
  port: 7010
spring:
  application:
    name: config-client-${server.port}
  
eureka:
  instance:
    instance-id: config-client-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka
config:
  version: 1